################################################################
#                                                              #
#         Playbook Ansible - Configuração de TLS               #
#         Criado por: Anselmo Borges                           #
#         Data de criação: 25.11.2019                          #
#         Ultima atualização: 25.11.2019                       #
#                                                              #
################################################################

- name: "Playbook Configuração de TLS no Cloudera"
  hosts: sp-vmw-hdp-dev-01

  tasks:
    - name: "1 - Cria o diretório todos no node principal"
      file:
        path: /tmp/teste/todos
        state: directory
      become: yes
      become_method: sudo
      become_user: root

    - name: "2 - Copia os arquivos .cer para o diretorio todos"
      shell: scp cdh@{{ item }}:/tmp/teste/*.cer /tmp/teste/todos/
      with_items:
        - sp-vmw-hdp-dev-01
        - sp-vmw-hdp-dev-02
        - sp-vmw-hdp-dev-03
        - sp-vmw-hdp-dev-04
        - sp-vmw-hdp-dev-05
        - sp-vmw-hdp-dev-06
        - sp-vmw-hdp-dev-07
        - sp-vmw-hdp-dev-08

    - name: "3 - Gera o server.pem com o conteudo dos arquivos .cer"
      shell: cat /tmp/teste/todos/{{ item }} >> /tmp/teste/server.pem
      with_items:
        - sp-vmw-hdp-dev-01.spcdc.br.cer
        - sp-vmw-hdp-dev-02.spcdc.br.cer
        - sp-vmw-hdp-dev-03.spcdc.br.cer
        - sp-vmw-hdp-dev-04.spcdc.br.cer
        - sp-vmw-hdp-dev-05.spcdc.br.cer
        - sp-vmw-hdp-dev-06.spcdc.br.cer
        - sp-vmw-hdp-dev-07.spcdc.br.cer
        - sp-vmw-hdp-dev-08.spcdc.br.cer

    - name: "4 - Distribui o server.pem para os hosts"
      shell: scp /tmp/teste/server.pem cdh@{{ item }}:/tmp/teste/server.pem
      with_items:
        - sp-vmw-hdp-dev-01
        - sp-vmw-hdp-dev-02
        - sp-vmw-hdp-dev-03
        - sp-vmw-hdp-dev-04
        - sp-vmw-hdp-dev-05
        - sp-vmw-hdp-dev-06
        - sp-vmw-hdp-dev-07
        - sp-vmw-hdp-dev-08
