################################################################
#                                                              #
#         Playbook Ansible - Configuração de TLS               #
#         Criado por: Anselmo Borges                           #
#         Data de criação: 25.11.2019                          #
#         Ultima atualização: 25.11.2019                       #
#                                                              #
################################################################                                    

- name: "Playbook Configuração de TLS no Cloudera"
  hosts: ndevs
  vars:
    path_python: "/opt/anaconda3/bin/python3"
    dest: "/tmp"
    python: "cria_certificados.py"
    dir: "/tmp/teste"
    pwd_novo: "#spclab@"

  tasks: 
    - name: "1 - Envia script Python de geração de certificados para os nodes"
      copy:
        src: python/{{ python }}
        dest: /tmp/{{ python }}
        owner: root
        group: root
        mode: 0644   
      become: yes
      become_method: sudo
      become_user: root

    - name: "2 - Executa Python nos nodes para a criação dos diretorios e certificados"
      command: '{{ path_python }} {{ dest }}/{{ python }} >> {{ dest }}/log_certificados.log'
      become: yes
      become_method: sudo
      become_user: root

    - name: "3 - Cria o arquivo de senha .passwd"
      shell: echo {{ pwd_novo }} > {{ dir }}/.passwd
      become: yes
      become_method: sudo
      become_user: root

    - name: "4 - Altera privilégios das pastas dos certificados para o cdh"
      shell: chown cdh:cdh -R {{ dir }}
      become: yes
      become_method: sudo
      become_user: root

